version: '3'
services:
  registry:
    container_name: registry
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
    restart: always
  
  manager:
    container_name: manager
    image: docker:18.06.3-ce-dind
    privileged: true
    tty: true
    ports:
      - 8000:80
      - 5000:5000
    expose: 3375
    depends_on:
      - registry
    command: "--insecure-registry registry:5000"
    volumes:
      - ./stack:./stack
  
  worker01:
    container_name: worker01
    image: docker:18.06.3-ce-dind
    privileged: true
    tty: true
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    depends_on:
      - registry
      - manager
    command: "--insecure-registry registry:5000"

  worker03:
    container_name: worker03
    image: docker:18.06.3-ce-dind
    privileged: true
    tty: true
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    depends_on:
      - registry
      - manager
    command: "--insecure-registry registry:5000"
  
  worker03:
    container_name: worker03
    image: docker:18.06.3-ce-dind
    privileged: true
    tty: true
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    depends_on:
      - registry
      - manager
    command: "--insecure-registry registry:5000"
